/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.sql.*;
import modelo.conexion;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO CELERON
 */
public class login extends javax.swing.JFrame {
    public static boolean controlMenu = false;
    public static String user = "";
    String pass = "";
    registrarse registrarse = new registrarse(); 
    /**
     * Creates new form login
     */
    public login() {
        initComponents();
       
        setResizable(false);
        setTitle("acceso");
        setLocationRelativeTo(null);
        
        
        TextPrompt usu = new TextPrompt("         username",txusername);
        TextPrompt pass = new TextPrompt("                 password",txcontraseña);
        
        ImageIcon wallpaper = new ImageIcon("src/images/logo.png");
        Icon logo = new ImageIcon(wallpaper.getImage().getScaledInstance(label_icono.getWidth(),
                label_icono.getHeight(), Image.SCALE_DEFAULT));
        label_icono.setIcon(logo);
        this.repaint();
        
    }
    @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/logo.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label_icono = new javax.swing.JLabel();
        txusername = new javax.swing.JTextField();
        txcontraseña = new javax.swing.JPasswordField();
        btnacceder = new javax.swing.JButton();
        btnregistrarse = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());

        txusername.setBackground(new java.awt.Color(255, 255, 255));
        txusername.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        txusername.setForeground(new java.awt.Color(0, 0, 0));
        txusername.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txusername.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        txusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txusernameActionPerformed(evt);
            }
        });

        txcontraseña.setBackground(new java.awt.Color(255, 255, 255));
        txcontraseña.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txcontraseña.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnacceder.setBackground(new java.awt.Color(0, 204, 0));
        btnacceder.setText("ACCEDER");
        btnacceder.setBorder(null);
        btnacceder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaccederActionPerformed(evt);
            }
        });

        btnregistrarse.setBackground(new java.awt.Color(0, 204, 0));
        btnregistrarse.setText("REGISTRARSE");
        btnregistrarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarseActionPerformed(evt);
            }
        });

        jLabel1.setText("creado por fernan  ®");
        jLabel1.setAlignmentX(2.0F);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("recuperar contraseña");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txusername, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txcontraseña)
                                .addComponent(btnacceder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnregistrarse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(label_icono, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(label_icono, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(txusername, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txcontraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnacceder, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnregistrarse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnaccederActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaccederActionPerformed
        user = txusername.getText().trim();
       
        pass = txcontraseña.getText().trim();
        
        if(!user.equals("") || !pass.equals("")){
            try{
            Connection cn = conexion.conectar();
            PreparedStatement ps = cn.prepareStatement(
            "select tipo_nivel, status from usuarios where username = '" + user 
                    + "' and contraseña = '" + pass + "'");
            
            ResultSet rs = ps.executeQuery();
            
            if(rs.next()){
                
                String tipo_nivel = rs.getString("tipo_nivel");
                String status = rs.getString("status");
                
                if(tipo_nivel.equalsIgnoreCase("administrador") && status.equalsIgnoreCase("activo")){
                   dispose();
                   new administrador().setVisible(true);
                }else if(tipo_nivel.equalsIgnoreCase("cliente") && status.equalsIgnoreCase("activo")){
                    dispose();
                   new cliente().setVisible(true);
                }else if(tipo_nivel.equalsIgnoreCase("usuario") && status.equalsIgnoreCase("activo")){
                    dispose();
                   new usuarios().setVisible(true);
                }
                
            }else{
             txusername.setBackground(Color.RED);
             txcontraseña.setBackground(Color.red);
             JOptionPane.showMessageDialog(null, "datos de acceso incorrectos");   
             txusername.setText("");
             txcontraseña.setText("");
            
            }
            }catch(SQLException e){
                System.err.println(e);
                JOptionPane.showMessageDialog(null, "error de conexion!!\ncontacte al administrador");
            }
        }else{
            JOptionPane.showMessageDialog(null, "debe llenar todos los campos");
        }
    }//GEN-LAST:event_btnaccederActionPerformed
 
    private void btnregistrarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarseActionPerformed
        if(controlMenu == false){
        registrarse.setVisible(true);
        }
              
            
       
    }//GEN-LAST:event_btnregistrarseActionPerformed

    private void txusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txusernameActionPerformed
            
    }//GEN-LAST:event_txusernameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnacceder;
    private javax.swing.JButton btnregistrarse;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel label_icono;
    private javax.swing.JPasswordField txcontraseña;
    private javax.swing.JTextField txusername;
    // End of variables declaration//GEN-END:variables
}
