/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import modelo.conexion;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
//import static ventanas.login.user;

/**
 *
 * @author LENOVO CELERON
 */
public class registrarse extends javax.swing.JFrame {

    /**
     * Creates new form registrarse
     */
    public registrarse() {
        initComponents();
        setResizable(false);
        setTitle("registrarse");
        setLocationRelativeTo(null);
        
        ImageIcon logoR = new ImageIcon("src/images/logo.png");
        Icon logo = new ImageIcon(logoR.getImage().getScaledInstance(logoregistro.getWidth(),
                logoregistro.getHeight(), Image.SCALE_DEFAULT));
        logoregistro.setIcon(logo);
        this.repaint();
    }
 @Override
    public Image getIconImage(){
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/logo.png"));
        return retValue;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txnombre = new javax.swing.JTextField();
        txemail = new javax.swing.JTextField();
        txtelefono = new javax.swing.JTextField();
        txusuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnguardar = new javax.swing.JButton();
        logoregistro = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txpass = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        txemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txemailActionPerformed(evt);
            }
        });

        txtelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtelefonoActionPerformed(evt);
            }
        });

        txusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txusuarioActionPerformed(evt);
            }
        });

        jLabel1.setText("nombre:");

        jLabel2.setText("email:");

        jLabel3.setText("telefono:");

        jLabel4.setText("ingrese un nombre de usuario:");

        jLabel5.setText("ingrese una contreseña:");

        btnguardar.setText("GUARDAR");
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("UNIVERSIDAD DE CORDOBA");

        txpass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txpassActionPerformed(evt);
            }
        });

        jLabel8.setText("Ingrese datos para su registro.");

        jLabel6.setText("creado por fernan  ®");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(96, 96, 96))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txnombre)
                                    .addComponent(txemail)
                                    .addComponent(txtelefono)
                                    .addComponent(txusuario)
                                    .addComponent(txpass, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(logoregistro, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(logoregistro, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnguardar)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txemailActionPerformed

    private void txtelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtelefonoActionPerformed

    private void txusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txusuarioActionPerformed

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        
            
          int validacion =0;
          String nombre,email,telefono,username,pass,nivel="",status="";
          nombre=txnombre.getText().trim();
          email= txemail.getText().trim();
          telefono = txtelefono.getText().trim();
          username= txusuario.getText().trim();
          pass = txpass.getText().trim();
          
          if(nombre.equals("")){
              txnombre.setBackground(Color.red);
              validacion++;
          }
          if(email.equals("")){
              txemail.setBackground(Color.red);
              validacion++;
          }
          if(telefono.equals("")){
              txtelefono.setBackground(Color.red);
               validacion++;
          }
          if(username.equals("")){
              txusuario.setBackground(Color.red);
               validacion++;
          }
          if(pass.equals("")){
              txpass.setBackground(Color.red);
               validacion++;
          }
          try{
             Connection cn = conexion.conectar(); 
             PreparedStatement pst = cn.prepareStatement("select username from usuarios where username = '" + username + "'" );
             ResultSet rs = pst.executeQuery();
             
             if(rs.next()){
                 txusuario.setBackground(Color.red);
                 JOptionPane.showMessageDialog(null, "nombre de usuario ya en uso");
                 cn.close();
             }else{
                 cn.close();
                 
                 if(validacion == 0){
                     
                  try{
                         
                     Connection cn2 = conexion.conectar();
                     PreparedStatement pst2 = cn2.prepareStatement("insert into usuarios values(?,?,?,?,?,?,?,?)");
                     
                     pst2.setInt(1, 0);
                     pst2.setString(2, nombre);
                     pst2.setString(3, email);
                     pst2.setString(4, telefono);
                     pst2.setString(5, username);
                     pst2.setString(6, pass);
                     pst2.setString(7, "usuario");
                     pst2.setString(8, "activo");
                     
                     pst2.executeUpdate();
                     cn2.close();
                     
                     limpiar();
                     txnombre.setBackground(Color.GREEN);
                     txemail.setBackground(Color.GREEN);
                     txtelefono.setBackground(Color.GREEN);
                     txusuario.setBackground(Color.GREEN);
                     txpass.setBackground(Color.GREEN);
                     
                     JOptionPane.showMessageDialog(null, "USARIO REGISTRADO" );
                       
                     }catch(SQLException e){
                         System.err.println("error al registrarte "+e);
                         JOptionPane.showMessageDialog(null, "error a la hora de registrarte" );
                     }
                     
                 }else{
                     JOptionPane.showMessageDialog(null, "debe llenar todo los campos" );
                 }
             }
          }catch(SQLException e){
              System.err.println(e);
              JOptionPane.showMessageDialog(null, "error" );
              
          }
        
    }//GEN-LAST:event_btnguardarActionPerformed

    private void txpassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txpassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txpassActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        login.controlMenu=false;
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registrarse.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new registrarse().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnguardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel logoregistro;
    private javax.swing.JTextField txemail;
    private javax.swing.JTextField txnombre;
    private javax.swing.JPasswordField txpass;
    private javax.swing.JTextField txtelefono;
    private javax.swing.JTextField txusuario;
    // End of variables declaration//GEN-END:variables
public void limpiar(){
    this.txnombre.setText("");
    this.txemail.setText("");
    this.txtelefono.setText("");
    this.txusuario.setText("");
    this.txpass.setText("");
}
}
