/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import modelo.conexion;
import java.awt.Color;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO CELERON
 */
public class usuarios extends javax.swing.JFrame {

    /**
     * Creates new form usuarios
     */
    public usuarios() {
        initComponents();
        setResizable(false);
         setTitle("usuario");
        setLocationRelativeTo(null);
        
         ImageIcon icono = new ImageIcon("src/images/logo.png");
        Icon l = new ImageIcon(icono.getImage().getScaledInstance(logo_usuarios.getWidth(),
                logo_usuarios.getHeight(), Image.SCALE_DEFAULT));
        logo_usuarios.setIcon(l);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jFileChooser1 = new javax.swing.JFileChooser();
        jButton1 = new javax.swing.JButton();
        logo_usuarios = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txcodigo = new javax.swing.JTextField();
        txcurso = new javax.swing.JTextField();
        txprofesor = new javax.swing.JTextField();
        txdia = new javax.swing.JTextField();
        txhoras = new javax.swing.JTextField();
        txhora = new javax.swing.JTextField();
        txsemestre = new javax.swing.JTextField();
        txcreditos = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        btnagregar = new javax.swing.JButton();
        btnmodificar = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnverh = new javax.swing.JButton();
        btnbuscar = new javax.swing.JButton();
        txbuscar = new javax.swing.JTextField();
        label = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnatras = new javax.swing.JButton();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setText("UNIVERSIDAD DE CORDOBA");

        jLabel2.setText("curso:");

        jLabel3.setText("profesor:");

        jLabel4.setText("dia:");

        jLabel5.setText("hora:");

        jLabel6.setText("horas:");

        jLabel7.setText("creditos:");

        jLabel8.setText("semestre:");

        jLabel9.setText("codigo:");

        txcodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txcodigoActionPerformed(evt);
            }
        });

        txcurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txcursoActionPerformed(evt);
            }
        });

        txprofesor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txprofesorActionPerformed(evt);
            }
        });

        txdia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txdiaActionPerformed(evt);
            }
        });

        txcreditos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txcreditosActionPerformed(evt);
            }
        });

        btnagregar.setText("AGREGAR");
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });

        btnmodificar.setText("MODIFICAR");
        btnmodificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodificarActionPerformed(evt);
            }
        });

        btneliminar.setText("ELIMINAR");
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });

        btnverh.setText("VER MI HORARIO");
        btnverh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnverhActionPerformed(evt);
            }
        });

        btnbuscar.setText("BUSCAR:");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        label.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N

        jLabel10.setText("Ingrese codigo para buscar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnbuscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txbuscar)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addComponent(btnverh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnagregar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnmodificar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btneliminar)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(label, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnagregar)
                        .addComponent(btnmodificar))
                    .addComponent(btneliminar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnverh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnbuscar)
                    .addComponent(txbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        btnatras.setText("SALIR");
        btnatras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnatrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(logo_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txhora, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txprofesor, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txcreditos, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jLabel8))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txcurso, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txdia, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txhoras, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txsemestre, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(btnatras)))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(logo_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel1)))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txcurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txprofesor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txdia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txhoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txhora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txcreditos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(txsemestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnatras)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txcodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txcodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txcodigoActionPerformed

    private void txcursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txcursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txcursoActionPerformed

    private void txprofesorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txprofesorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txprofesorActionPerformed

    private void txdiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txdiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txdiaActionPerformed

    private void txcreditosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txcreditosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txcreditosActionPerformed

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
         String curso,profesor,dia,hora;
        String idcurso,idcliente,horas,codigo,semestre,creditos;
        int validacion =0;
        
        codigo = txcodigo.getText().trim();
        curso = txcurso.getText().trim();
        profesor = txprofesor.getText().trim();
        dia = txdia.getText().trim();
        hora = txhora.getText().trim();
        horas = txhoras.getText().trim();
        creditos = txcreditos.getText().trim();
        semestre = txsemestre.getText().trim();
        
        if(codigo.equals("") || curso.equals("") || profesor.equals("") || dia.equals("") ||
           hora.equals("") || horas.equals("") || creditos.equals("") || semestre.equals("")){
            
            txcodigo.setBackground(Color.red);
            txcurso.setBackground(Color.red);
            txprofesor.setBackground(Color.red);
            txdia.setBackground(Color.red);
            txhora.setBackground(Color.red);
            txhoras.setBackground(Color.red);
            txcreditos.setBackground(Color.red);
            txsemestre.setBackground(Color.red);
            
            JOptionPane.showMessageDialog(null, "debe llenar todos los campos");
            
        }else{
           try{
        Connection cn = conexion.conectar();
        PreparedStatement pst = cn.prepareStatement("insert into cursos values(?,?,?,?,?,?,?,?,?,?,?)"); 
        
        pst.setInt(1, 0);
        pst.setInt(2, 0);
        pst.setString(3, codigo);
        pst.setString(4, curso);
        pst.setString(5, profesor);
        pst.setString(6, dia);
        pst.setString(7, hora);
        pst.setString(8, horas);
        pst.setString(9, semestre);
        pst.setString(10, creditos);
        pst.setString(11, "");
        pst.executeUpdate();
        
        cn.close();
        
        txcodigo.setText("");
        txcurso.setText("");
        txprofesor.setText("");
        txdia.setText("");
        txhora.setText("");
        txhoras.setText("");
        txcreditos.setText("");
        txsemestre.setText("");
        
        label.setText("registro exitoso");
        
        }catch(SQLException e){
            System.err.println("error al guardar curso " + e);
             JOptionPane.showMessageDialog(null, "error\n contacte a su proovedor de software");
        }
         
        }
        
        
        
    }//GEN-LAST:event_btnagregarActionPerformed

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
         try{
          Connection con = conexion.conectar(); 
          PreparedStatement pst = con.prepareStatement("delete from cursos where codigo = ?");
          
          pst.setString(1, txbuscar.getText().trim());
          pst.executeUpdate();
          
          txcodigo.setText("");
          txcurso.setText("");
          txprofesor.setText("");
          txdia.setText("");
          txhoras.setText("");
          txhora.setText("");
          txcreditos.setText("");
          txsemestre.setText("");
          
          label.setText("curso eliminado");
          
       }catch(SQLException e){
           System.err.println(e);
           JOptionPane.showMessageDialog(null, "error de software");
       }
    }//GEN-LAST:event_btneliminarActionPerformed

    private void btnverhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnverhActionPerformed
        try{
          vistacursosu v = new vistacursosu();
        v.setVisible(true); 
        
        }catch(Exception e){
            
        }
        
    }//GEN-LAST:event_btnverhActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
        try{
          Connection con = conexion.conectar();
         PreparedStatement ps = con.prepareStatement("select * from cursos where codigo = ?"); 
         ps.setString(1, txbuscar.getText().trim());
         
         ResultSet rs = ps.executeQuery();
         
         if(rs.next()){
             txcodigo.setText(rs.getString("codigo"));
             txcurso.setText(rs.getString("curso"));
             txprofesor.setText(rs.getString("profesor"));
             txdia.setText(rs.getString("dia"));
             txhora.setText(rs.getString("hora"));
             txhoras.setText(rs.getString("horas"));
             txcreditos.setText(rs.getString("creditos"));
             txsemestre.setText(rs.getString("semestre"));
         }else{
             label.setText("no disponible");
         }
         }catch(SQLException e){
             System.err.println(e);
             JOptionPane.showMessageDialog(null, "error de software");
         }
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btnmodificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodificarActionPerformed
        String codigo = txbuscar.getText().trim();
    
    try{
     Connection c = conexion.conectar();
     PreparedStatement p = c.prepareStatement("UPDATE cursos SET codigo = ?, curso = ?, profesor = ?, dia = ?, hora = ?, horas = ?, creditos = ?, semestre = ?  WHERE codigo = " +codigo);
    
     p.setString(1, txcodigo.getText().trim());
     p.setString(2, txcurso.getText().trim());
     p.setString(3, txprofesor.getText().trim());
     p.setString(4, txdia.getText().trim());
     p.setString(5, txhora.getText().trim());
     p.setString(6, txhoras.getText().trim());
     p.setString(7, txcreditos.getText().trim());
     p.setString(8, txsemestre.getText().trim());
     
     p.executeUpdate();
     
     JOptionPane.showMessageDialog(null, "curso modificado");
    }catch(SQLException e){
        System.err.println("error al guardar curso " + e);
        JOptionPane.showMessageDialog(null, "error\n contacte a su proovedor de software");
    }
    }//GEN-LAST:event_btnmodificarActionPerformed

    private void btnatrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnatrasActionPerformed
        dispose();
        new login().setVisible(true);
        
    }//GEN-LAST:event_btnatrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(usuarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new usuarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btnatras;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnmodificar;
    private javax.swing.JButton btnverh;
    private javax.swing.JButton jButton1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel label;
    private javax.swing.JLabel logo_usuarios;
    private javax.swing.JTextField txbuscar;
    private javax.swing.JTextField txcodigo;
    private javax.swing.JTextField txcreditos;
    private javax.swing.JTextField txcurso;
    private javax.swing.JTextField txdia;
    private javax.swing.JTextField txhora;
    private javax.swing.JTextField txhoras;
    private javax.swing.JTextField txprofesor;
    private javax.swing.JTextField txsemestre;
    // End of variables declaration//GEN-END:variables
}
